spring:
  application:
    name: order-service

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    open-in-view: false

  liquibase:
    change-log: classpath:/db/changelog/db.changelog-master.xml
    enabled: true

server:
  port: 8082

user-service:
  url: ${USER_SERVICE_URL:http://localhost:8081}

resilience4j:
  circuitbreaker:
    instances:
      userService:
        sliding-window-size: 5
        failure-rate-threshold: 50
        wait-duration-in-open-state: 10s
        permitted-number-of-calls-in-half-open-state: 2
        register-health-indicator: true